# Generated by Django 4.0.3 on 2022-04-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_votes_profile_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='votes',
        ),
        migrations.AddField(
            model_name='profile',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
