# Generated by Django 4.0.3 on 2022-04-08 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(default='author', max_length=100),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=models.TextField(default='content'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 20, 58, 3, 767920)),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
