# Generated by Django 4.0.3 on 2022-04-08 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(default='match', max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 4, 8, 21, 14, 43, 939411))),
                ('result', models.TextField(default='result')),
            ],
        ),
    ]
