# Generated by Django 4.0.3 on 2022-04-08 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_remove_score_match_remove_score_result_score_score1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score1',
            new_name='score_1',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='score2',
            new_name='score_2',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='team1',
            new_name='team_1',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='team2',
            new_name='team_2',
        ),
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 21, 18, 1, 300902)),
        ),
    ]
