# Generated by Django 4.0.3 on 2022-04-08 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_rename_score1_score_score_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 21, 18, 9, 733907)),
        ),
    ]
