# Generated by Django 4.0.3 on 2022-04-09 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0009_alter_score_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 11, 20, 10, 982601)),
        ),
    ]
