# Generated by Django 4.0.3 on 2022-04-09 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0011_alter_score_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 22, 6, 45, 15137)),
        ),
    ]
