# Generated by Django 4.0.3 on 2022-04-09 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0015_alter_score_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 2, 9, 20, 957907)),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
