# Generated by Django 4.0.3 on 2022-04-22 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0017_alter_score_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 15, 13, 53, 873533)),
        ),
    ]
