# Generated by Django 4.0.3 on 2022-04-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q0', models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E')], max_length=100)),
                ('q1', models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E')], max_length=100)),
                ('q2', models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E')], max_length=100)),
                ('q3', models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E')], max_length=100)),
                ('q4', models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E')], max_length=100)),
                ('q5', models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E')], max_length=100)),
                ('q6', models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E')], max_length=100)),
                ('q7', models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E')], max_length=100)),
                ('q8', models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E')], max_length=100)),
                ('q9', models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E')], max_length=100)),
            ],
        ),
    ]
