# Generated by Django 4.0.3 on 2022-04-22 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizAnswers',
            new_name='QuizAnswer',
        ),
    ]
