# Generated by Django 4.0.3 on 2022-04-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_quizanswers_quizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='name',
            field=models.CharField(default='name', max_length=32),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='q0',
            field=models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='q1',
            field=models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='q2',
            field=models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='q3',
            field=models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='q4',
            field=models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='q5',
            field=models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='q6',
            field=models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='q7',
            field=models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='q8',
            field=models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='q9',
            field=models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E')], max_length=1),
        ),
    ]
