# Generated by Django 4.0.3 on 2022-04-09 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=100)),
                ('author', models.CharField(default='author', max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 4, 9, 10, 48, 31, 583765))),
                ('content', models.TextField(default='content')),
            ],
        ),
    ]
