# Generated by Django 4.0.3 on 2022-04-09 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_alter_forumpost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='reply',
            field=models.CharField(default='author - 2022-04-09 11:19:00.730826', max_length=100),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 11, 19, 0, 730826)),
        ),
    ]
