# Generated by Django 4.0.3 on 2022-04-09 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_alter_forumpost_date_alter_forumpost_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 11, 25, 7, 946610)),
        ),
    ]
