# Generated by Django 3.2.7 on 2022-04-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('league', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=20)),
            ],
        ),
    ]
